# Generated by Django 5.1.7 on 2025-04-08 04:42

from django.db import migrations

def create_units(apps, schema_editor):
    Unit = apps.get_model('recipes', 'Unit')
    units = [
        ('teaspoon', 'tsp'),
        ('tablespoon', 'tbsp'),
        ('cup', 'cup'),
        ('ounce', 'oz'),
        ('gram', 'g'),
        ('each', 'ea'),
    ]
    for name, abbrev in units:
        Unit.objects.get_or_create(name=name, abbreviation=abbrev)

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_create_dishingredient_model'),
    ]

    operations = [
        migrations.RunPython(create_units),
    ]
