# Generated by Django 5.1.7 on 2025-04-08 04:42

from django.db import migrations, models

def migrate_ingredients(apps, schema_editor):
    Dish = apps.get_model('recipes', 'Dish')
    DishIngredient = apps.get_model('recipes', 'DishIngredient')
    Unit = apps.get_model('recipes', 'Unit')
    
    default_unit = Unit.objects.first()
    
    for dish in Dish.objects.all():
        for ingredient in dish.ingredients.all():
            DishIngredient.objects.create(
                dish=dish,
                ingredient=ingredient,
                quantity=1,
                unit=default_unit
            )

class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_populate_initial_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.DishIngredient',
                to='recipes.Ingredient'
            ),
        ),
        migrations.RunPython(migrate_ingredients),
    ]
