# Generated by Django 5.1.7 on 2025-05-26 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_grocery_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Quantity must be greater than 0')]),
        ),
    ]
