# Generated by Django 5.1.7 on 2025-04-04 21:01

import django.core.validators
import django.db.models.deletion
import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This ingredient name already exist.'}, max_length=100, unique=True)),
                ('unit', models.CharField(blank=True, choices=[('g', 'grams'), ('ml', 'milliliters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('pcs', 'pieces')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Item to buy')),
            ],
            options={
                'verbose_name_plural': 'Groceries',
                'ordering': ['-purchased', 'ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This dish name already exist.'}, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('prep_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Prep time must be at least 1 minute.'), django.core.validators.MaxValueValidator(1440, message='Prep time cannot exceed 24 hours.')])),
                ('cook_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0, message='Cook time cannot be negative.'), django.core.validators.MaxValueValidator(1440, message='Cook time cannot exceed 24 hours.')])),
                ('image', models.ImageField(blank=True, help_text='Upload image (max 5MB, 3000x3000px, JPG/PNG/WEBP)', upload_to='dish_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), recipes.models.Dish.validate_image_size, recipes.models.Dish.validate_image_dimensions])),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
    ]
