# Generated by Django 5.1.7 on 2025-04-05 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('instruction', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='step_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.dish')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('dish', 'step_number')},
            },
        ),
    ]
