# Generated by Django 5.1.7 on 2025-05-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_change_ingredients_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['-in_cart', 'ingredient__name'], 'verbose_name_plural': 'Groceries'},
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='purchased',
        ),
        migrations.AddField(
            model_name='grocery',
            name='in_cart',
            field=models.BooleanField(default=False, help_text='Check if this item is in your cart', verbose_name='Added to cart'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='abbreviation',
            field=models.CharField(blank=True, error_messages={'unique': 'This abbreviation already exists.'}, max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(error_messages={'unique': 'This unit name already exists.'}, max_length=20, unique=True),
        ),
    ]
