# Generated by Django 5.1.7 on 2025-05-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_grocery_options_remove_grocery_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='is_optional',
            field=models.BooleanField(default=False, help_text='Check if this item is optional', verbose_name='Optional'),
        ),
    ]
