# Generated by Django 5.1.7 on 2025-05-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_dishingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_cart', models.BooleanField(default=False, help_text='Check if this item is in your cart', verbose_name='Added to cart')),
                ('is_optional', models.BooleanField(default=False, help_text='Check if this item is optional', verbose_name='Optional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.unit')),
            ],
            options={
                'verbose_name_plural': 'Grocery Items',
                'ordering': ['-in_cart', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Grocery',
        ),
    ]
